version: '3'
services:
  product-service:
    image: nshigarov/product-service:latest
    container_name: product-service
    ports:
      - "8081:8081"
    networks:
      - product-review-network

networks:
  product-review-network:
    external: true
